import React, { useState } from 'react';
import { Briefcase, CheckCircle2, MapPin, Wrench } from 'lucide-react';
import { Incident } from '../types';

interface FieldOperationsConsoleProps { incidents: Incident[]; onUpdateIncident: (updated: Incident) => void; }

export const FieldOperationsConsole: React.FC<FieldOperationsConsoleProps> = ({ incidents, onUpdateIncident }) => {
  const [selectedId, setSelectedId] = useState<string | null>(incidents[0]?.id ?? null);
  const [notes, setNotes] = useState('');
  const assigned = incidents.filter((incident) => incident.assignedOfficerId && incident.status !== 'Resolved' && incident.status !== 'Rejected');
  const active = assigned.find((incident) => incident.id === selectedId) ?? assigned[0];
  const complete = () => { if (!active) return; const now = new Date().toISOString(); onUpdateIncident({ ...active, status: 'Resolved', resolvedAt: now, resolutionNotes: notes, updatedAt: now, timeline: [...active.timeline, { id: `timeline-${Date.now()}`, timestamp: now, title: 'Work completed', description: notes || 'Field work marked complete.', actor: active.assignedOfficerName || 'Assigned officer', role: 'Officer', statusChangedTo: 'Resolved' }] }); setNotes(''); };

  return <div className="mx-auto max-w-7xl space-y-8 px-4 py-8 sm:px-6 lg:px-8">
    <header className="border-b border-slate-800 pb-6"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-cyan-400"><Briefcase className="h-4 w-4" /> Field operations</p><h1 className="mt-1 font-heading text-3xl font-extrabold text-white">Assigned work orders</h1><p className="mt-1 text-sm text-slate-400">Update only incidents assigned to your authenticated field account.</p></header>
    {assigned.length === 0 ? <section className="glass-panel rounded-2xl border border-dashed border-slate-700 p-12 text-center"><Briefcase className="mx-auto h-8 w-8 text-slate-600" /><h2 className="mt-4 text-base font-semibold text-slate-200">No active assignments</h2><p className="mt-1 text-sm text-slate-500">You currently have no incidents assigned to you.</p></section> : <div className="grid gap-6 lg:grid-cols-[20rem_1fr]"><aside className="glass-panel rounded-2xl border border-slate-800 p-4"><h2 className="text-sm font-semibold text-white">My queue ({assigned.length})</h2><div className="mt-4 space-y-2">{assigned.map((incident) => <button type="button" key={incident.id} onClick={() => setSelectedId(incident.id)} className={`w-full rounded-xl border p-3 text-left ${active?.id === incident.id ? 'border-cyan-400 bg-cyan-500/10' : 'border-slate-800 bg-slate-900/60'}`}><span className="font-mono text-xs text-cyan-400">{incident.id}</span><span className="mt-1 block truncate text-xs font-semibold text-white">{incident.title}</span><span className="mt-1 block truncate text-[11px] text-slate-500">{incident.address}</span></button>)}</div></aside><section className="glass-panel rounded-2xl border border-slate-800 p-6">{active && <><span className="font-mono text-xs text-cyan-400">{active.id}</span><h2 className="mt-2 text-xl font-bold text-white">{active.title}</h2><p className="mt-2 flex items-center gap-1 text-xs text-slate-400"><MapPin className="h-3.5 w-3.5" />{active.address}</p><div className="mt-6 rounded-xl border border-slate-800 bg-slate-950/60 p-4"><p className="text-xs text-slate-400">{active.description}</p><label className="mt-4 block text-xs font-semibold text-slate-300">Completion notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={4} className="mt-2 w-full rounded-lg border border-slate-800 bg-slate-900 p-3 text-sm text-white" /></label><button type="button" onClick={complete} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-3 text-xs font-semibold text-white hover:bg-emerald-500"><Wrench className="h-4 w-4" />Mark work complete</button></div></>}</section></div>}
  </div>;
};
